# Generated by Django 4.1.7 on 2023-03-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentData',
        ),
    ]
