# Generated by Django 4.1.7 on 2023-03-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/users_images/')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=500)),
                ('credit', models.CharField(max_length=50)),
            ],
        ),
    ]
