# Generated by Django 4.1.7 on 2023-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_componentdata_image_name_alter_componentdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=500)),
                ('credit', models.CharField(max_length=50)),
            ],
        ),
    ]
